apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw==
  rmq-pass: Z3Vlc3Q=
  aws_access_key_id: QUtJQTVETFFZU1dKQjJHN0E2NTY=
  aws_secret_access_key: aXk3b29UbVlBUUI0dTNPSVFhRWNha0ZqVUp2aGdjT3NHQUpxSkpqcg==

