apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::960446693452:user/kops-admin
      username: system:node:ip-172-31-0-130.us-east-2.compute.internal
      groups:
        - system:bootstrappers
        - system:nodes
