apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::900569011602:user/kopsadmin
      username: system:node:{{kubevpro.shariqdevops.online}}
      groups:
        - system:bootstrappers
        - system:nodes
