apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpro-db-data-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0e1499197fa6e80dc
    fsType: ext4
