apiVersion: v1
kind: PersistentVolume
metadata:
  name: vpro-db-pvc
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0676f281e794c9001
    fsType: ext4