apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpro-db-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      pv-name: vpro-db-data-pv
  storageClassName: "my-storage-class"
