apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: shariqazeem/vprofiledb:V1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
        ports:
        - containerPort: 3306
          name: vprodb-port
        volumeMounts:
        - name: vpro-db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: vpro-db-data
        persistentVolumeClaim:
          claimName: vpro-db-pvc
